# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-30 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u041f\u043e\u0432\u0442\u043e\u0440')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': '\u0418\u0441\u0442\u043e\u0440\u0438\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u043e\u043a',
                'verbose_name_plural': '\u0418\u0441\u0442\u043e\u0440\u0438\u0438 \u043e\u0442\u043f\u0440\u0430\u0432\u043e\u043a',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u0418\u043c\u044f')),
                ('surname', models.CharField(max_length=30, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u041f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a',
                'verbose_name_plural': '\u041f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='SubscriberList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('subscribers', models.TextField(blank=True, max_length=2000, verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a\u0438')),
                ('number', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u041a\u043e\u043b-\u0432\u043e')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': '\u0421\u043f\u0438\u0441\u043e\u043a \u043f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a\u043e\u0432',
                'verbose_name_plural': '\u0421\u043f\u0438\u0441\u043a\u0438 \u043f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('subject', models.CharField(max_length=50, verbose_name='\u0422\u0435\u043c\u0430')),
                ('file', models.FileField(help_text='.html', upload_to='templates/', verbose_name='\u041c\u0430\u043a\u0435\u0442 (.html)')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u041c\u0430\u043a\u0435\u0442',
                'verbose_name_plural': '\u041c\u0430\u043a\u0435\u0442\u044b',
            },
        ),
        migrations.AddField(
            model_name='subscriber',
            name='list',
            field=models.ManyToManyField(blank=True, to='sendman.SubscriberList', verbose_name='\u0421\u043f\u0438\u0441\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='sendhistory',
            name='rcpt_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sendman.SubscriberList', verbose_name='\u0410\u0434\u0440\u0435\u0441\u0430\u0442'),
        ),
        migrations.AddField(
            model_name='sendhistory',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sendman.Template', verbose_name='\u041c\u0430\u043a\u0435\u0442'),
        ),
    ]
